Master1Addr         = "127.0.0.1"            # Master1的地址
Master2Addr         = "127.0.0.2"            # Master2的地址
SlaveAddrs          = []                          # Slave的地址列表
Password            = "{PBE}HYvqT5rdH0_st-nXTJjV_eBiCqXXK008Oq0B7irUnfw"             # Root用户密码
Port                = 3306                        # MySQL 端口号
ReplUsr             = "repl"                      # 复制用用户名
ReplPassword        = "{PBE}bnJ6RVW0A8STdxnHetEkzG0gSN1snB4Qc243EujuCi4"             # 复制用户密码
MySQLCnf            = "/etc/my.cnf"               # MySQL 配置文件的地址

HAProxyCfg          = "/etc/haproxy.cfg"          # HAProxy配置文件地址
HAProxyRestartShell = "systemctl restart haproxy" # HAProxy重启命令

Debug               = false                       # 测试模式，只打印SQL和HAProxy配置, 不实际执行
LocalAddr           = ""                          # 指定本机地址，不指定则自动从网卡中获取

